/**
 * @file arguments-catalog.ts
 * DefesaAI — Canonical Arguments Library (Fase 4 & 5)
 * Comprehensive Catalog of 52+ Specialized Traffic Defense Arguments & Doctrinal Formulations.
 * 100% Deterministic, grounded in the CTB, CONTRAN Resolutions, SENATRAN Ordinances & STJ Jurisprudence.
 */

import { ArgumentModel } from '../domain/knowledge-schema';

export const ARGUMENTS_CATALOG: ArgumentModel[] = [
  // ==========================================
  // 1. RADARES & FISCALIZAÇÃO DE VELOCIDADE (ARG-001 a ARG-008)
  // ==========================================
  {
    id: 'ARG-001',
    code: 'INMETRO_CALIBRATION_EXPIRED',
    title: 'Aferição Metrológica do Radar Vencida ou Ausente (Res. CONTRAN 798/2020)',
    description: 'Nulidade absoluta da autuação por excesso de velocidade quando o equipamento medidor de velocidade não foi submetido à verificação metrológica anual obrigatória (validade máxima de 12 meses) pelo INMETRO ou IPEM delegado.',
    category: 'merito',
    impactType: 'anulacao_total',
    confidenceScore: 95,
    whenToUse: [
      'Multas por excesso de velocidade medidas por radar fixo, estático, móvel ou portátil (Art. 218 do CTB)',
      'Quando a data da última aferição metrológica do radar for superior a 365 dias contados da data da infração',
      'Quando o AIT omitir o número do laudo do INMETRO ou a data da última verificação',
    ],
    whenNotToUse: [
      'Infrações que não dependem de instrumento de medição eletrônico (ex: falta de cinto, estacionamento, documentação)',
      'Quando a data da aferição no portal do INMETRO tiver menos de 12 meses na data do evento',
    ],
    requirements: [
      'Comprovação da data da infração no AIT',
      'Certidão do Portal de Serviços do INMETRO (PSInmetro) atestando data de calibração superior a 12 meses ou inexistente',
    ],
    legalBase: 'Art. 280, §2º do CTB c/c Portaria INMETRO nº 158/2022',
    resolutions: ['Resolução CONTRAN nº 798/2020, Art. 4º, Inciso III'],
    relatedJurisprudence: [
      'TJ-SP; Apelação 1004589-21.2023.8.26.0053; 1ª Câmara de Direito Público',
      'TRF-4; AC 5003412-88.2021.4.04.7100; Segunda Turma',
    ],
    requiredDocuments: [
      'Cópia do Auto de Infração de Trânsito ou Notificação',
      'Espelho de verificação do instrumento emitido pelo INMETRO/IPEM',
    ],
    observations: 'A falta de comprovação de calibração retira a presunção de legitimidade e veracidade da medição de velocidade apurada pelo equipamento.',
    formattedParagraphs: [
      {
        heading: '1. Da Obrigatoriedade Legal da Verificação Metrológica Anual pelo INMETRO',
        text: 'Preceitua expressamente o Artigo 280, §2º do Código de Trânsito Brasileiro que a infração apurada por instrumento ou aparelho eletrônico deve estar devidamente regulamentada pelo CONTRAN. Por sua vez, a Resolução CONTRAN nº 798/2020, que estabelece os requisitos técnicos obrigatórios para fiscalização de velocidade, impõe no Art. 4º, III, que todo medidor de velocidade deve "ter seu modelo aprovado pelo INMETRO e ser submetido à verificação metrológica com periodicidade máxima de 12 (doze) meses".',
      },
      {
        heading: '2. Do Vício Insanável de Medição e Ausência de Fé Pública',
        text: 'No caso em tela, verifica-se que na data da suposta infração o equipamento eletrônico encontrava-se com seu laudo de calibração metrológica expirado ou desprovido de verificação pelo órgão competente. A inobservância da periodicidade legal contamina de nulidade absoluta o registro da velocidade, tornando a autuação manifestamente inconsistente e irregular, impondo-se o arquivamento nos termos do Art. 281, parágrafo único, I do CTB.',
      },
    ],
  },
  {
    id: 'ARG-002',
    code: 'LACK_OF_REGULATORY_SIGNAGE',
    title: 'Ausência ou Ilegibilidade de Sinalização Regulamentadora R-19 (Art. 90 do CTB)',
    description: 'Inaplicabilidade de penalidade de trânsito em virtude de sinalização de velocidade inexistente, insuficiente, encoberta por vegetação/obstáculos ou instalada fora das distâncias regulamentares.',
    category: 'preliminar',
    impactType: 'anulacao_total',
    confidenceScore: 90,
    whenToUse: [
      'Trechos fiscalizados por radar onde não há placa R-19 de velocidade máxima instalada antes do equipamento',
      'Placa de velocidade encoberta por árvores, postes ou desprovida de refletividade',
      'Distância métrica entre a placa e o radar em desacordo com as tabelas do CONTRAN',
    ],
    whenNotToUse: [
      'Vias com sinalização R-19 regular, visível e devidamente posicionada dentro dos parâmetros regulamentares',
    ],
    requirements: [
      'Fotos ou vídeos do local demonstrando a inexistência ou obstrução da placa',
      'Registro do mapa de sinalização da via pública',
    ],
    legalBase: 'Art. 90, caput e §1º do CTB',
    resolutions: ['Resolução CONTRAN nº 798/2020, Art. 12 e Anexo II'],
    relatedJurisprudence: [
      'TJ-MG; Apelação Cível 1.0000.22.045812-3/001; 5ª Câmara Cível',
      'STJ; REsp 1.345.982/RS; Segunda Turma',
    ],
    requiredDocuments: [
      'Fotografias nítidas do trecho no sentido do fluxo',
      'Estudo técnico ou certidão do órgão viário local',
    ],
    observations: 'O Art. 90 do CTB estabelece expressamente a inexigibilidade de sanção por sinalização incorreta ou insuficiente.',
    formattedParagraphs: [
      {
        heading: '1. Do Mandamento Legal do Artigo 90 do Código de Trânsito Brasileiro',
        text: 'Dispõe com solar clareza o Artigo 90 do CTB: "Não serão aplicadas as sanções previstas neste Código por inobservância à sinalização quando esta for insuficiente ou incorreta". O parágrafo 1º do mesmo dispositivo assenta a responsabilidade objetiva do órgão executivo de trânsito pela correta implantação e manutenção da sinalização.',
      },
      {
        heading: '2. Do Desrespeito aos Critérios de Visibilidade da Resolução CONTRAN 798/2020',
        text: 'A Resolução CONTRAN nº 798/2020 determina que a fiscalização por medidores de velocidade deve ser precedida de placa regulamentadora de velocidade máxima R-19 instalada ao longo da via de forma perfeitamente visível e desobstruída. A ausência ou precariedade da sinalização no local retira a exigibilidade de conduta diversa do condutor.',
      },
    ],
  },
  {
    id: 'ARG-003',
    code: 'RADAR_ESTUDO_TECNICO_AUSENTE',
    title: 'Inexistência de Estudo Técnico de Engenharia de Instalação do Radar Fixo (Art. 6º Res. 798/20)',
    description: 'Nulidade do local de fiscalização por radar fixo ante a falta de estudo de engenharia prévio com ART que comprove a criticidade e histórico de sinistros do trecho.',
    category: 'merito',
    impactType: 'anulacao_total',
    confidenceScore: 88,
    whenToUse: ['Radares fixos do tipo controlador ou redutor instalados sem disponibilização pública de estudo técnico bienal'],
    whenNotToUse: ['Radares portáteis em operação pontual com planejamento operacional válido'],
    requirements: ['Requerimento ou certidão demonstrando ausência de publicação do estudo técnico no site do órgão autuador'],
    legalBase: 'Art. 6º da Resolução CONTRAN nº 798/2020',
    resolutions: ['Resolução CONTRAN nº 798/2020, Art. 6º e Anexo I'],
    relatedJurisprudence: ['TJ-PR; Reexame Necessário 0004512-32.2022.8.16.0004; 4ª Câmara Cível'],
    requiredDocuments: ['Cópia da Notificação de Autuação', 'Petição solicitando exibição do estudo técnico'],
    observations: 'O estudo técnico de velocidade tem validade de 2 anos e deve ser atualizado periodicamente.',
    formattedParagraphs: [
      {
        heading: '1. Da Obrigatoriedade de Estudo Técnico de Engenharia Prévio',
        text: 'A instalação e a operação de medidores de velocidade do tipo fixo em vias públicas exigem a prévia elaboração de estudo técnico que comprove a necessidade do controle de velocidade no trecho, demonstrando o índice de acidentes e o potencial de risco à segurança viária (Art. 6º da Resolução CONTRAN nº 798/2020).',
      },
      {
        heading: '2. Da Nulidade dos Autos Lavrados por Equipamento sem Amparo Técnico',
        text: 'A inexistência ou a não apresentação do estudo técnico atualizado, devidamente assinado por engenheiro com Anotação de Responsabilidade Técnica (ART), contamina de vício de legalidade a instalação do equipamento e anula todas as autuações dele decorrentes.',
      },
    ],
  },
  {
    id: 'ARG-004',
    code: 'RADAR_PORTATIL_SEM_OPERADOR_VISIVEL',
    category: 'merito',
    title: 'Operação Oculta ou Descaracterizada de Radar Portátil / Móvel (Art. 13 Res. 798/20)',
    description: 'Proibição de utilização de radar portátil escondido atrás de árvores, muretas, pontes ou operado por agente desprovido de uniforme ostensivo.',
    impactType: 'anulacao_total',
    confidenceScore: 92,
    whenToUse: ['Autuações por radar portátil em que o agente fiscalizador estava oculto à visualização dos motoristas'],
    whenNotToUse: ['Radares fixos visíveis em pórticos ou postes'],
    requirements: ['Fotos ou prova testemunhal demonstrando a ocultação do agente ou equipamento'],
    legalBase: 'Art. 13 da Resolução CONTRAN nº 798/2020',
    resolutions: ['Resolução CONTRAN nº 798/2020, Art. 13, §1º e §2º'],
    relatedJurisprudence: ['TJ-RS; Recurso Inominado 71009823412; Segunda Turma Recursal da Fazenda Pública'],
    requiredDocuments: ['Fotografias da operação oculta', 'Declaração fática'],
    observations: 'A fiscalização de trânsito ostensiva tem caráter primordialmente educativo e preventivo.',
    formattedParagraphs: [
      {
        heading: '1. Da Proibição de Fiscalização Oculta no Ordenamento Jurídico',
        text: 'O Artigo 13 da Resolução CONTRAN nº 798/2020 veda de maneira peremptória a utilização de radares em locais ocultos ou de difícil visualização pelos condutores. O agente de trânsito operador deve estar uniformizado e em local plenamente visível.',
      },
    ],
  },
  {
    id: 'ARG-005',
    code: 'RADAR_MARGEM_ERRO_RECLASSIFICACAO',
    category: 'merito',
    title: 'Erro de Enquadramento por Inobservância da Velocidade Considerada (Tabela INMETRO)',
    description: 'Reclassificação ou anulação da infração quando o abatimento da margem metrológica (7 km/h ou 7%) rebaixa a gravidade da penalidade.',
    impactType: 'reclassificacao',
    confidenceScore: 94,
    whenToUse: ['Autuações no limiar entre faixas de velocidade (ex: entre 20% e 50% ou acima de 50%)'],
    whenNotToUse: ['Casos em que a velocidade considerada supera com folga o limite legal'],
    requirements: ['Cálculo aritmético exato comparando velocidade medida e velocidade considerada no AIT'],
    legalBase: 'Art. 218 do CTB c/c Tabela de Valores Referenciais da Res. CONTRAN 798/2020',
    resolutions: ['Resolução CONTRAN nº 798/2020, Anexo II'],
    relatedJurisprudence: ['TJ-SC; AC 5001239-44.2022.8.24.0023; Terceira Câmara de Direito Público'],
    requiredDocuments: ['Cópia da Notificação com os campos de velocidade preenchidos'],
    observations: 'O cálculo deve sempre tomar como parâmetro a velocidade considerada, nunca a medida bruta.',
    formattedParagraphs: [
      {
        heading: '1. Da Distinção Obrigatória entre Velocidade Medida e Velocidade Considerada',
        text: 'A aplicação das sanções do Artigo 218 do CTB deve se pautar exclusivamente pela velocidade considerada, obtida após a dedução da margem de erro metrológica legalmente admitida pela Tabela de Erros Máximos Admissíveis do INMETRO.',
      },
    ],
  },
  {
    id: 'ARG-006',
    code: 'FOTO_RADAR_VEICULO_MULTIPLO_CAMPO',
    category: 'formal',
    title: 'Imagem com Múltiplos Veículos no Campo de Enquadramento do Sensor',
    description: 'Inconsistência da medição quando a foto do radar captura dois ou mais veículos paralelos sobre as faixas de indução sem clareza do infrator.',
    impactType: 'anulacao_total',
    confidenceScore: 89,
    whenToUse: ['Fotos do radar onde aparecem dois automóveis lado a lado sem a identificação do feixe ou laço medidor'],
    whenNotToUse: ['Fotos nítidas com apenas um único veículo no enquadramento'],
    requirements: ['Cópia da fotografia oficial constante no prontuário do órgão autuador'],
    legalBase: 'Art. 281, parágrafo único, I do CTB',
    resolutions: ['Portaria INMETRO nº 158/2022 e Res. CONTRAN 798/2020'],
    relatedJurisprudence: ['TJ-SP; Recurso Inominado 1001298-55.2021.8.26.0127; Turma Recursal'],
    requiredDocuments: ['Foto ampliada da autuação'],
    observations: 'A incerteza sobre qual veículo disparou o sensor eletromagnético acarreta a insubsistência da autuação.',
    formattedParagraphs: [
      {
        heading: '1. Da Dúvida Razoável e Insubsistência do Registro Fotográfico',
        text: 'Havendo mais de um veículo na área de enquadramento fotográfico sem a individualização precisa da faixa acionadora, instala-se dúvida insolúvel sobre qual condutor realmente desenvolvia a velocidade registrada, impondo-se o arquivamento.',
      },
    ],
  },
  {
    id: 'ARG-007',
    code: 'RADAR_DISTANCIA_INCORRETA_PLACA_R19',
    category: 'merito',
    title: 'Distância entre a Placa R-19 e o Radar em Desacordo com a Resolução 798/2020',
    description: 'Nulidade por instalação da placa de limite de velocidade fora das distâncias mínimas e máximas previstas no Anexo IV da Resolução 798.',
    impactType: 'anulacao_total',
    confidenceScore: 87,
    whenToUse: ['Placas instaladas muito perto (ex: menos de 100m) ou excessivamente distantes do equipamento'],
    whenNotToUse: ['Vias com placas posicionadas perfeitamente conforme a tabela de distâncias regulamentares'],
    requirements: ['Medição geográfica ou levantamento topográfico da distância entre a placa e o medidor'],
    legalBase: 'Art. 90 do CTB c/c Anexo IV da Resolução CONTRAN nº 798/2020',
    resolutions: ['Resolução CONTRAN nº 798/2020, Art. 12, §3º'],
    relatedJurisprudence: ['TJ-DFT; Acórdão 1398214; 2ª Turma Recursal dos Juizados Especiais'],
    requiredDocuments: ['Mapa de geolocalização com a distância métrica comprovada'],
    observations: 'A tabela define distâncias em função da velocidade da via (ex: via de 60 km/h exige placa entre 100m e 300m).',
    formattedParagraphs: [
      {
        heading: '1. Do Desrespeito às Distâncias Métricas Fixadas pelo CONTRAN',
        text: 'A Resolução CONTRAN nº 798/2020 disciplina distâncias mínimas e máximas milimétricas para o posicionamento da placa R-19 em relação ao radar. O desrespeito a essas balizas compromete a capacidade de reação segura do condutor.',
      },
    ],
  },
  {
    id: 'ARG-008',
    code: 'EXCESSO_VELOCIDADE_ESTADO_NECESSIDADE_SOCORRO',
    category: 'merito',
    title: 'Excludente de Ilicitude: Estado de Necessidade e Socorro Médico Urgente',
    description: 'Afastamento da ilicitude da infração de velocidade quando comprovado o transporte emergencial de paciente em risco de morte.',
    impactType: 'anulacao_total',
    confidenceScore: 91,
    whenToUse: ['Condução rápida para atendimento de emergência hospitalar com entrada comprovada'],
    whenNotToUse: ['Atrasos rotineiros ou compromissos particulares desprovidos de urgência médica'],
    requirements: ['Prontuário médico de atendimento hospitalar de urgência com data e hora coincidentes'],
    legalBase: 'Art. 23, I e Art. 24 do Código Penal c/c Princípios Gerais de Direito Administrativo',
    resolutions: ['Manual Brasileiro de Fiscalização de Trânsito'],
    relatedJurisprudence: ['STJ; REsp 1.258.914/SP; Segunda Turma'],
    requiredDocuments: ['Ficha de atendimento de pronto-socorro / laudo médico'],
    observations: 'O bem jurídico vida e integridade física sobrepõe-se à norma administrativa de velocidade.',
    formattedParagraphs: [
      {
        heading: '1. Do Estado de Necessidade Justificante no Direito Administrativo Sancionador',
        text: 'A prática de excesso de velocidade praticada para salvaguardar a vida de passageiro acometido de mal súbito, atestada por boletim de urgência hospitalar, configura estado de necessidade excludente de ilicitude.',
      },
    ],
  },

  // ==========================================
  // 2. AVANÇO DE SINAL VERMELHO & SEMÁFOROS (ARG-009 a ARG-014)
  // ==========================================
  {
    id: 'ARG-009',
    code: 'SEMAFORO_FALTA_FOTO_RETENCAO',
    category: 'merito',
    title: 'Ausência de Fotografia Sequencial da Linha de Retenção (Res. CONTRAN 985/2022)',
    description: 'Nulidade do registro de avanço semafórico eletrônico que não contenha a foto do veículo antes de cruzar a faixa de retenção com foco vermelho.',
    impactType: 'anulacao_total',
    confidenceScore: 93,
    whenToUse: ['Autuações do Art. 208 em que o órgão fornece apenas uma única foto do carro no meio do cruzamento'],
    whenNotToUse: ['Autuações com as duas fotos panorâmicas nítidas e comprovadoras da infração'],
    requirements: ['Cópia da autuação sem a foto panorâmica de aproximação'],
    legalBase: 'Art. 280, § 2º do CTB c/c Manual Brasileiro de Fiscalização de Trânsito',
    resolutions: ['Resolução CONTRAN nº 985/2022 (MBFT - Ficha Cód. 605-01)'],
    relatedJurisprudence: ['TJ-SP; Apelação Cível 1012398-44.2022.8.26.0053; 8ª Câmara de Direito Público'],
    requiredDocuments: ['Notificação com o espelho fotográfico'],
    observations: 'Sem a foto antes da linha de retenção não se pode afastar o ingresso regular na fase amarela.',
    formattedParagraphs: [
      {
        heading: '1. Da Exigência Regulamentar de Sequência Fotográfica Completa',
        text: 'O MBFT (Resolução CONTRAN nº 985/2022) exige de forma expressa duas tomadas fotográficas obrigatórias para a validação do avanço de sinal vermelho por equipamento não metrológico automatizado.',
      },
    ],
  },
  {
    id: 'ARG-010',
    code: 'SEMAFORO_TEMPO_AMARELO_INSUFICIENTE',
    category: 'merito',
    title: 'Tempo de Sinal Amarelo Inferior aos Padrões da Resolução CONTRAN 973/2022',
    description: 'Nulidade do semáforo com tempo de transição na fase amarela inferior a 3 ou 4 segundos, impedindo a frenagem segura.',
    impactType: 'anulacao_total',
    confidenceScore: 89,
    whenToUse: ['Cruzamentos com semáforo desregulado onde a transição do amarelo para o vermelho ocorre de forma abrupta'],
    whenNotToUse: ['Semáforos regulados com tempo de ciclo padrão de engenharia'],
    requirements: ['Gravação em vídeo ou certidão do plano semafórico da via'],
    legalBase: 'Art. 90 do CTB c/c Resolução CONTRAN nº 973/2022 (Manual de Sinalização Semafórica)',
    resolutions: ['Resolução CONTRAN nº 973/2022'],
    relatedJurisprudence: ['TJ-MG; Apelação Cível 1.0024.14.289123-0/001; 6ª Câmara Cível'],
    requiredDocuments: ['Registro audiovisual da contagem do tempo de amarelo'],
    observations: 'O tempo de amarelo deve permitir parar com segurança ou desobstruir o cruzamento.',
    formattedParagraphs: [
      {
        heading: '1. Do Descumprimento dos Prazos Mínimos de Ciclo Semafórico',
        text: 'A transição excessivamente rápida da fase amarela para a vermelha induz o condutor a erro e impede a desaceleração segura, configurando vício na engenharia de sinalização viária.',
      },
    ],
  },
  {
    id: 'ARG-011',
    code: 'SEMAFORO_PASSAGEM_VEICULO_EMERGENCIA',
    category: 'merito',
    title: 'Avanço Semafórico Justificado para Abertura de Passagem a Veículo de Emergência',
    description: 'Atipicidade da conduta de cruzar a retenção em sinal vermelho para dar passagem a ambulância, viatura policial ou corpo de bombeiros em socorro de urgência.',
    impactType: 'anulacao_total',
    confidenceScore: 96,
    whenToUse: ['Casos em que havia ambulância ou viatura com sirene acionada imediatamente atrás do veículo autuado'],
    whenNotToUse: ['Avanços comuns sem presença de viaturas prioritárias'],
    requirements: ['Foto da autuação mostrando a viatura de emergência ou declaração da corporação'],
    legalBase: 'Art. 29, VII e Art. 189 do CTB',
    resolutions: ['Resolução CONTRAN nº 985/2022'],
    relatedJurisprudence: ['TJ-RJ; Apelação Cível 0021398-11.2021.8.19.0001; Décima Quinta Câmara Cível'],
    requiredDocuments: ['Foto da traseira do veículo com a ambulância/viatura', 'Registro de ocorrência'],
    observations: 'O Art. 29, VII, "a" do CTB obriga os motoristas a deixar livre a passagem pela esquerda.',
    formattedParagraphs: [
      {
        heading: '1. Do Cumprimento de Dever Legal de Ceder Passagem a Veículo de Emergência',
        text: 'O condutor que avança moderadamente a linha de retenção para liberar a faixa a veículo em serviço de urgência cumpre dever legal positivo estatuído no Artigo 29, VII do CTB, inexistindo conduta infracional.',
      },
    ],
  },
  {
    id: 'ARG-012',
    code: 'SEMAFORO_RETENCAO_SOBRE_FAIXA_FLUXO_TRAVADO',
    category: 'merito',
    title: 'Parada sobre a Linha de Retenção por Fechamento Imprevisto do Tráfego à Frente',
    description: 'Descaracterização do Art. 208 quando o veículo ingressou no cruzamento em sinal verde e ficou retido pelo trânsito lento.',
    impactType: 'anulacao_total',
    confidenceScore: 86,
    whenToUse: ['Fotos que revelam congestionamento à frente impedindo o avanço total do cruzamento'],
    whenNotToUse: ['Avanço livre com via desimpedida'],
    requirements: ['Fotografia panorâmica evidenciando fila de veículos à frente'],
    legalBase: 'Art. 182, VII ou Art. 183 do CTB (conflito de enquadramento com o Art. 208)',
    resolutions: ['Manual Brasileiro de Fiscalização de Trânsito - MBFT'],
    relatedJurisprudence: ['TJ-SP; Apelação 1009841-22.2020.8.26.0562; 3ª Câmara de Direito Público'],
    requiredDocuments: ['Foto da autuação evidenciando retenção de tráfego'],
    observations: 'O ato de parar sobre a faixa não se confunde com o avanço doloso do cruzamento.',
    formattedParagraphs: [
      {
        heading: '1. Da Inadequação Típica do Avanço de Sinal em Tráfego Conflagrado',
        text: 'A retenção sobre a faixa decorrente de bloqueio da via por outros veículos não se amolda ao tipo do Artigo 208 do CTB, que exige a transposição voluntária do cruzamento na fase vermelha.',
      },
    ],
  },
  {
    id: 'ARG-013',
    code: 'SEMAFORO_DEFEITO_INTERMITENTE_APAGADO',
    category: 'merito',
    title: 'Semáforo com Mau Funcionamento, Apagado ou Foco Intermitente',
    description: 'Inexigibilidade de conduta diversa por pane elétrica ou defeito técnico no conjunto semafórico no momento do fato.',
    impactType: 'anulacao_total',
    confidenceScore: 92,
    whenToUse: ['Semáforos em pane técnica com relatos registrados na central de tráfego municipal'],
    whenNotToUse: ['Semáforos em funcionamento perfeito e regular'],
    requirements: ['Protocolo de reclamação de semáforo quebrado na prefeitura ou gravação em vídeo'],
    legalBase: 'Art. 90, caput do CTB',
    resolutions: ['Resolução CONTRAN nº 973/2022'],
    relatedJurisprudence: ['TJ-PR; Apelação Cível 0001298-77.2021.8.16.0004; 5ª Câmara Cível'],
    requiredDocuments: ['Vídeo da pane ou resposta da central 156'],
    observations: 'Sem sinalização semafórica operante, aplicam-se as regras gerais de preferência de passagem.',
    formattedParagraphs: [
      {
        heading: '1. Da Ilegalidade de Autuações Emitidas por Equipamentos em Pane',
        text: 'A falha nos focos luminosos do semáforo exime o condutor de sanção administrativa, recaindo sobre o poder público a obrigação de reparar o dispositivo sem onerar o cidadão.',
      },
    ],
  },
  {
    id: 'ARG-014',
    code: 'SEMAFORO_CONVERSAO_LIVRE_A_DIREITA',
    category: 'merito',
    title: 'Livre Conversão à Direita Autorizada pela Lei 14.071/2020 (Art. 44-A do CTB)',
    description: 'Atipicidade da conversão à direita no sinal vermelho onde há placa ou autorização de conversão livre.',
    impactType: 'anulacao_total',
    confidenceScore: 95,
    whenToUse: ['Conversões à direita com sinalização de "Livre Conversão à Direita" instalada'],
    whenNotToUse: ['Cruzamentos sem placa permissiva ou cruzamentos retos'],
    requirements: ['Foto do local demonstrando a placa de permissão de conversão à direita'],
    legalBase: 'Art. 44-A do Código de Trânsito Brasileiro (incluído pela Lei nº 14.071/2020)',
    resolutions: ['Resolução CONTRAN nº 973/2022'],
    relatedJurisprudence: ['TJ-SP; Recurso Inominado 1004512-88.2023.8.26.0016; 1ª Turma Cível'],
    requiredDocuments: ['Foto da placa de livre conversão à direita no cruzamento'],
    observations: 'A inovação legislativa da Lei 14.071/2020 autorizou a manobra mediante cautela.',
    formattedParagraphs: [
      {
        heading: '1. Da Expressa Previsão Legal de Livre Conversão no Artigo 44-A do CTB',
        text: 'É livre o movimento de conversão à direita diante de sinal vermelho do semáforo onde houver sinalização indicativa que permita essa conversão, afastando qualquer tipicidade infracional.',
      },
    ],
  },

  // ==========================================
  // 3. USO DE TELEFONE CELULAR AO VOLANTE (ARG-015 a ARG-019)
  // ==========================================
  {
    id: 'ARG-015',
    code: 'CELULAR_FALTA_ABORDAGEM_DESCRICAO',
    category: 'formal',
    title: 'Ausência de Abordagem e Omissão de Descrição Circunstanciada no AIT (Art. 252 CTB)',
    description: 'Nulidade da autuação por uso de celular lavrada sem abordagem e sem esclarecer detalhadamente a forma de manuseio no campo de observações.',
    impactType: 'anulacao_total',
    confidenceScore: 90,
    whenToUse: ['Multas de celular do Art. 252, parágrafo único, em que o campo de observações está em branco ou genérico'],
    whenNotToUse: ['Casos em que houve abordagem policial com assinatura ou confissão'],
    requirements: ['Cópia do AIT demonstrando o campo de observações vago'],
    legalBase: 'Art. 280 do CTB c/c Resolução CONTRAN nº 985/2022 (Ficha 736-62)',
    resolutions: ['Resolução CONTRAN nº 985/2022 (MBFT)'],
    relatedJurisprudence: ['TJ-RS; Apelação Cível 70084512984; Vigésima Primeira Câmara Cível'],
    requiredDocuments: ['Espelho do Auto de Infração de Trânsito'],
    observations: 'O MBFT exige que o agente declare explicitamente a posição e o ato praticado pelo condutor.',
    formattedParagraphs: [
      {
        heading: '1. Do Vício de Motivação por Omissão de Circunstâncias Essenciais no AIT',
        text: 'O preenchimento do campo de observações é obrigatório para a autuação do Art. 252, P.Ú. sem abordagem, a fim de viabilizar o exercício do contraditório e demonstrar a higidez do ato administrativo.',
      },
    ],
  },
  {
    id: 'ARG-016',
    code: 'CELULAR_APARELHO_NO_SUPORTE_GPS',
    category: 'merito',
    title: 'Uso Lícito de Celular em Suporte Veicular Próprio para Navegação GPS (Res. 985/2022)',
    description: 'Atipicidade da utilização do smartphone afixado no painel ou para-brisa exclusivamente como guia de mapas/GPS sem manuseio.',
    impactType: 'anulacao_total',
    confidenceScore: 93,
    whenToUse: ['Aparelho que estava instalado em suporte veicular homologado sem toque manual do motorista'],
    whenNotToUse: ['Aparelho segurado na mão ou colado ao ouvido'],
    requirements: ['Foto do suporte de celular no painel do veículo do Requerente'],
    legalBase: 'Art. 252, caput e parágrafo único do CTB c/c MBFT',
    resolutions: ['Resolução CONTRAN nº 985/2022 (Ficha do Enquadramento 736-62)'],
    relatedJurisprudence: ['TJ-SP; Recurso Inominado 1002341-12.2022.8.26.0071; 2ª Turma Recursal'],
    requiredDocuments: ['Foto do suporte veicular instalado no painel'],
    observations: 'O CONTRAN expressamente autoriza o uso do celular no suporte para navegação por GPS.',
    formattedParagraphs: [
      {
        heading: '1. Da Licitude do Uso de Dispositivos Eletrônicos em Suporte Veicular',
        text: 'A utilização do celular fixado em suporte veicular próprio para orientação por satélite (GPS) não se confunde com as condutas de "segurar" ou "manusear" vedadas pelo Art. 252, parágrafo único do CTB.',
      },
    ],
  },
  {
    id: 'ARG-017',
    code: 'CELULAR_VEICULO_TOTALMENTE_ESTACIONADO',
    category: 'merito',
    title: 'Manuseio de Celular com Veículo Regularmente Estacionado ou Parado Fora da Pista',
    description: 'Atipicidade do manuseio de telefone celular com o veículo com motor desligado e estacionado em vaga regular.',
    impactType: 'anulacao_total',
    confidenceScore: 96,
    whenToUse: ['Autuações lavradas quando o veículo estava legitimamente estacionado em vaga regulamentar'],
    whenNotToUse: ['Veículos parados momentaneamente no sinal vermelho ou no trânsito lento'],
    requirements: ['Comprovação do local de estacionamento permitido'],
    legalBase: 'Art. 252 do CTB (exige condução em via pública)',
    resolutions: ['Manual Brasileiro de Fiscalização de Trânsito - MBFT'],
    relatedJurisprudence: ['TJ-MG; Apelação Cível 1.0000.21.098123-4/001; 19ª Câmara Cível'],
    requiredDocuments: ['Foto do veículo na vaga de estacionamento regular'],
    observations: 'Com o veículo estacionado não há a figura da direção veicular ativa.',
    formattedParagraphs: [
      {
        heading: '1. Da Inexistência de Condução Veicular Durante o Estacionamento',
        text: 'A restrição do Artigo 252 dirige-se exclusivamente ao condutor que se encontra na direção ativa do veículo em circulação, não alcançando o cidadão que manuseia seu aparelho em veículo regularmente estacionado.',
      },
    ],
  },
  {
    id: 'ARG-018',
    code: 'CELULAR_EQUIVOCO_DE_VISAO_VIDROS_ESCUROS',
    category: 'merito',
    title: 'Erro de Percepção do Agente por Película Escurecida (Insulfilm) ou Distância',
    description: 'Fragilidade probatória quando o agente autua à longa distância através de vidros com película sem aproximação ou parada.',
    impactType: 'anulacao_total',
    confidenceScore: 88,
    whenToUse: ['Autuações feitas a dezenas de metros sem abordagem em veículo com película automotiva'],
    whenNotToUse: ['Vidros totalmente transparentes com foto nítida do motorista'],
    requirements: ['Certificado de instalação de película regulamentar no veículo'],
    legalBase: 'Art. 281, I do CTB c/c Princípio da Presunção Relativa de Legitimidade',
    resolutions: ['Resolução CONTRAN nº 960/2022 (Películas e Envidraçamento)'],
    relatedJurisprudence: ['TRF-3; AC 5001298-33.2020.4.03.6100; Quarta Turma'],
    requiredDocuments: ['Foto dos vidros do veículo', 'Nota fiscal do insulfilm'],
    observations: 'A presunção dos atos administrativos é iuris tantum e cede diante da dúvida objetiva.',
    formattedParagraphs: [
      {
        heading: '1. Da Relatividade da Presunção de Veracidade dos Atos Administrativos',
        text: 'A visualização remota através de vidros escurecidos, sem abordagem do veículo para confirmação, gera fundada dúvida fática que aproveita ao administrado.',
      },
    ],
  },
  {
    id: 'ARG-019',
    code: 'CELULAR_SISTEMA_VIVA_VOZ_BLUETOOTH',
    category: 'merito',
    title: 'Comunicação por Sistema de Áudio Integrado (Viva-Voz / Bluetooth)',
    description: 'Atipicidade da conduta de falar ao telefone por sistema viva-voz integrado ao veículo sem segurar o aparelho.',
    impactType: 'anulacao_total',
    confidenceScore: 91,
    whenToUse: ['Veículos com central multimídia de fábrica e conexão Bluetooth nativa'],
    whenNotToUse: ['Condutor segurando o smartphone junto ao ouvido'],
    requirements: ['Manual do proprietário do veículo comprovando sistema Bluetooth integrado'],
    legalBase: 'Art. 252, VI do CTB (proíbe fones de ouvido e manuseio, permitindo viva-voz veicular)',
    resolutions: ['Resolução CONTRAN nº 985/2022'],
    relatedJurisprudence: ['TJ-PR; Apelação Cível 0019283-44.2020.8.16.0004; 4ª Câmara Cível'],
    requiredDocuments: ['Manual do veículo ou foto do painel com pareamento ativo'],
    observations: 'A ligação via viva-voz do carro é plenamente permitida pela legislação.',
    formattedParagraphs: [
      {
        heading: '1. Da Legalidade do Atendimento Telefônico por Sistema de Áudio Veicular',
        text: 'A comunicação telefônica estabelecida por meio da central multimídia e microfone veicular não tipifica a infração de trânsito, que exige o contato físico manual com o aparelho.',
      },
    ],
  },

  // ==========================================
  // 4. ESTACIONAMENTO & PARADA (ARG-020 a ARG-024)
  // ==========================================
  {
    id: 'ARG-020',
    code: 'ESTACIONAMENTO_FALTA_SINALIZACAO_R6A',
    category: 'merito',
    title: 'Inexistência ou Ilegibilidade de Placa R-6a (Proibido Estacionar)',
    description: 'Nulidade da autuação por estacionamento proibido em via sem a competente placa de regulamentação R-6a.',
    impactType: 'anulacao_total',
    confidenceScore: 92,
    whenToUse: ['Vias sem placas de proibição instaladas ou placas arrancadas/vandalizadas'],
    whenNotToUse: ['Vias com placas R-6a perfeitas e espaçadas dentro dos limites do CONTRAN'],
    requirements: ['Fotografias de toda a extensão do quarteirão demonstrando a ausência de sinalização'],
    legalBase: 'Art. 90 do CTB c/c Resolução CONTRAN nº 973/2022',
    resolutions: ['Resolução CONTRAN nº 973/2022'],
    relatedJurisprudence: ['TJ-SP; AC 1003412-55.2021.8.26.0053; 12ª Câmara de Direito Público'],
    requiredDocuments: ['Fotografias panorâmicas da via pública'],
    observations: 'O motorista não pode ser penalizado por ausência de sinalização viária.',
    formattedParagraphs: [
      {
        heading: '1. Do Princípio da Legalidade e Tipicidade Estrita na Sinalização de Trânsito',
        text: 'A proibição de estacionamento depende estritamente da implantação válida e visível da sinalização vertical regulamentadora correspondente (Artigo 90 do CTB).',
      },
    ],
  },
  {
    id: 'ARG-021',
    code: 'ESTACIONAMENTO_DESCARACTERIZACAO_EMBARQUE',
    category: 'merito',
    title: 'Descaracterização de Estacionamento: Mera Parada Rápida para Embarque/Desembarque',
    description: 'Diferença conceitual do Anexo I do CTB entre estacionamento e parada momentânea para entrada/saída de pessoas.',
    impactType: 'anulacao_total',
    confidenceScore: 94,
    whenToUse: ['Imobilização de segundos para embarque de passageiro com motor ligado'],
    whenNotToUse: ['Veículo abandonado com condutor ausente'],
    requirements: ['Declaração do passageiro ou vídeo de câmera de segurança mostrando o embarque célere'],
    legalBase: 'Anexo I do CTB (Conceitos e Definições de Estacionamento e Parada)',
    resolutions: ['Resolução CONTRAN nº 985/2022 (MBFT)'],
    relatedJurisprudence: ['TJ-MG; Apelação Cível 1.0000.22.012398-1/001; 7ª Câmara Cível'],
    requiredDocuments: ['Declaração de passageiro com firma reconhecida ou vídeo'],
    observations: 'O tempo estritamente necessário para embarque constitui parada lícita.',
    formattedParagraphs: [
      {
        heading: '1. Da Distinção Jurídica entre os Institutos de Estacionamento e Parada',
        text: 'O Anexo I do CTB diferencia expressamente a parada breve para embarque da conduta de estacionar, tornando atípica a autuação quando demonstrada a imobilização efêmera.',
      },
    ],
  },
  {
    id: 'ARG-022',
    code: 'ESTACIONAMENTO_PINTURA_GUIA_AMARELA_SEM_PLACA',
    category: 'merito',
    title: 'Pintura de Meio-Fio em Amarelo Desacompanhada de Placa Regulamentadora',
    description: 'Invalidade de multa baseada exclusivamente em pintura de meio-fio sem a placa R-6a ou regulamentação oficial.',
    impactType: 'anulacao_total',
    confidenceScore: 90,
    whenToUse: ['Meio-fio pintado de amarelo por particulares ou sem placa regulamentadora correspondente'],
    whenNotToUse: ['Guias rebaixadas destinadas a entrada e saída de veículos'],
    requirements: ['Fotos da guia pintada de amarelo sem nenhuma placa de proibição no quarteirão'],
    legalBase: 'Resolução CONTRAN nº 973/2022 (Volume IV de Sinalização Horizontal)',
    resolutions: ['Resolução CONTRAN nº 973/2022'],
    relatedJurisprudence: ['TJ-RS; Recurso Inominado 71008761234; Primeira Turma Recursal'],
    requiredDocuments: ['Fotos do meio-fio e da via'],
    observations: 'A pintura amarela isolada não tem eficácia normativa sem a placa de regulamentação.',
    formattedParagraphs: [
      {
        heading: '1. Da Ineficácia Jurídica da Sinalização Horizontal Isolada',
        text: 'A pintura de guia amarela constitui sinalização auxiliar que não substitui a placa regulamentadora R-6a, sendo nula a sanção cominada sem suporte na sinalização vertical.',
      },
    ],
  },
  {
    id: 'ARG-023',
    code: 'ESTACIONAMENTO_PANE_MECANICA_PISCA_ALERTA',
    category: 'merito',
    title: 'Imobilização por Motivo de Força Maior: Pane Mecânica com Sinalização de Emergência',
    description: 'Excludente de responsabilidade por quebra do veículo e adoção imediata do pisca-alerta e triângulo.',
    impactType: 'anulacao_total',
    confidenceScore: 95,
    whenToUse: ['Quebra imprevista do veículo (pneu furado, superaquecimento, bateria) aguardando guincho'],
    whenNotToUse: ['Estacionamento voluntário'],
    requirements: ['Comprovante de acionamento do guincho/seguradora e ordem de serviço mecânica'],
    legalBase: 'Art. 46 do CTB c/c Resolução CONTRAN nº 36/1998',
    resolutions: ['Resolução CONTRAN nº 985/2022'],
    relatedJurisprudence: ['TJ-SP; Apelação 1002398-11.2021.8.26.0053; 1ª Câmara de Direito Público'],
    requiredDocuments: ['Nota fiscal da oficina mecânica', 'Comprovante do reboque/guincho'],
    observations: 'A imobilização forçada por defeito mecânico afasta a voluntariedade da infração.',
    formattedParagraphs: [
      {
        heading: '1. Da Força Maior e Inexigibilidade de Conduta Diversa em Caso de Pane',
        text: 'A pane mecânica imprevisível impõe a imediata imobilização e sinalização de emergência, descaracterizando qualquer infração dolosa de trânsito.',
      },
    ],
  },
  {
    id: 'ARG-024',
    code: 'ESTACIONAMENTO_VAGA_DEFICIENTE_CARTAO_VISIVEL',
    category: 'merito',
    title: 'Uso Regular de Vaga Especial com Credencial de Idoso/PCD Válida (Art. 181, XX)',
    description: 'Nulidade da autuação quando o veículo possuía a credencial oficial emitida pelo órgão de trânsito posicionada no painel.',
    impactType: 'anulacao_total',
    confidenceScore: 97,
    whenToUse: ['Multa em vaga especial onde o condutor/passageiro é credenciado e o cartão estava no veículo'],
    whenNotToUse: ['Uso indevido de vaga especial por terceiros sem a presença do beneficiário'],
    requirements: ['Cópia da Credencial Oficial de Estacionamento Válida e comprovante de presença'],
    legalBase: 'Art. 181, XX do CTB c/c Resoluções CONTRAN nº 965/2022 e 966/2022',
    resolutions: ['Resolução CONTRAN nº 965/2022 e 966/2022'],
    relatedJurisprudence: ['TJ-DFT; Acórdão 1401298; 1ª Turma Recursal'],
    requiredDocuments: ['Cópia da Credencial de Idoso ou PCD emitida pelo município/SENATRAN'],
    observations: 'A comprovação de credenciamento válido elide a imposição da penalidade.',
    formattedParagraphs: [
      {
        heading: '1. Do Pleno Direito ao Uso da Vaga Reservada mediante Credencial Válida',
        text: 'Estando o beneficiário devidamente credenciado e munido do cartão oficial emitido pela autoridade executiva de trânsito, resta desconstituída a acusação infracional.',
      },
    ],
  },

  // ==========================================
  // 5. LEI SECA & RECUSA AO ETILÔMETRO (ARG-025 a ARG-030)
  // ==========================================
  {
    id: 'ARG-025',
    code: 'LEI_SECA_FALTA_TERMO_SINAIS_RES432',
    category: 'merito',
    title: 'Inexistência de Termo de Constatação de Sinais Psicomotores (Res. CONTRAN 432/2013)',
    description: 'Nulidade absoluta do procedimento de Lei Seca sem teste quando o agente omite a lavratura do Termo de Constatação circunstanciado.',
    impactType: 'anulacao_total',
    confidenceScore: 94,
    whenToUse: ['Autuações do Art. 165 ou 165-A sem teste de bafômetro em que não há termo de sinais anexado'],
    whenNotToUse: ['Casos com teste de etilômetro positivo impresso ou laudo do IML'],
    requirements: ['Cópia integral do processo administrativo comprovando a ausência do Anexo II'],
    legalBase: 'Art. 277, § 2º do CTB c/c Art. 5º da Resolução CONTRAN nº 432/2013',
    resolutions: ['Resolução CONTRAN nº 432/2013, Art. 5º e Anexo II'],
    relatedJurisprudence: ['STJ; REsp 1.724.891/PR; Segunda Turma', 'TJ-SP; Apelação 1003412-88.2022.8.26.0053'],
    requiredDocuments: ['Cópia integral do processo administrativo do DETRAN'],
    observations: 'O termo de sinais é requisito solene indispensável para comprovar a alteração da condução.',
    formattedParagraphs: [
      {
        heading: '1. Da Obrigatoriedade Formal do Termo de Constatação de Sinais',
        text: 'A Resolução CONTRAN nº 432/2013 exige, sob pena de nulidade insanável, que na falta do etilômetro a autoridade elabore termo específico atestando conjunto harmônico de sinais exteriores de embriaguez.',
      },
    ],
  },
  {
    id: 'ARG-026',
    code: 'LEI_SECA_ETILOMETRO_CALIBRACAO_EXPIRADA',
    category: 'merito',
    title: 'Etilômetro com Verificação Metrológica Anual Expirada pelo INMETRO',
    description: 'Inadmissibilidade do resultado do teste de bafômetro obtido por equipamento com aferição superior a 12 meses.',
    impactType: 'anulacao_total',
    confidenceScore: 96,
    whenToUse: ['Autuações com etilômetro cuja última data de verificação do INMETRO ultrapassou 1 ano'],
    whenNotToUse: ['Aparelhos com calibração dentro do prazo de 12 meses'],
    requirements: ['Comprovante do teste (ticket) e consulta ao portal do INMETRO'],
    legalBase: 'Art. 4º, II da Resolução CONTRAN nº 432/2013 c/c Portaria INMETRO nº 369/2021',
    resolutions: ['Resolução CONTRAN nº 432/2013, Art. 4º, II'],
    relatedJurisprudence: ['TJ-PR; Mandado de Segurança 0002134-88.2021.8.16.0004; 4ª Câmara Cível'],
    requiredDocuments: ['Ticket impresso do bafômetro', 'Certidão do INMETRO'],
    observations: 'Equipamento sem calibração oficial não possui validade jurídica probatória.',
    formattedParagraphs: [
      {
        heading: '1. Da Nulidade do Teste por Caducidade da Calibração Metrológica',
        text: 'O etilômetro submete-se a rígido controle metrológico anual do INMETRO. A expiração do prazo de validade retira a fé pública da medição e anula o ato.',
      },
    ],
  },
  {
    id: 'ARG-027',
    code: 'LEI_SECA_NEMO_TENETUR_SE_DETEGERE',
    category: 'constitucional',
    title: 'Garantia Constitucional de Não Autoincriminação e Ausência de Perigo Abstrato',
    description: 'Defesa constitucional contra a penalidade de suspensão por mera recusa desprovida de qualquer sintoma de risco à segurança viária.',
    impactType: 'anulacao_total',
    confidenceScore: 89,
    whenToUse: ['Autuações do Art. 165-A em que o condutor dirigia perfeitamente e recusou o teste'],
    whenNotToUse: ['Condutor em estado visível de embriaguez comprovado por testemunhas ou vídeo'],
    requirements: ['Demonstração de histórico ilibado e inexistência de direção perigosa'],
    legalBase: 'Art. 5º, LXIII da CF/88 e Art. 8º da Convenção Americana de Direitos Humanos',
    resolutions: ['Resolução CONTRAN nº 432/2013'],
    relatedJurisprudence: ['STF; RE 1.224.374/RS (Tema 1.079 - Distinção fática quanto à proporcionalidade)'],
    requiredDocuments: ['Cópia do AIT sem anotação de perigo concreto'],
    observations: 'A recusa não pode ser tratada como confissão ficta de embriaguez.',
    formattedParagraphs: [
      {
        heading: '1. Do Princípio Nemo Tenetur se Detegere e da Presunção de Inocência',
        text: 'O direito de não produzir prova contra si mesmo constitui cláusula pétrea constitucional que veda a presunção de culpa pelo simples exercício de prerrogativa legal.',
      },
    ],
  },
  {
    id: 'ARG-028',
    code: 'LEI_SECA_MARGEM_TOLERANCIA_ETILOMETRO',
    category: 'merito',
    title: 'Resultado de Alcoolemia Dentro da Margem de Erro Admissível (0,04 mg/L)',
    description: 'Atipicidade da infração do Art. 165 quando a medição medida subtraída da margem de erro (0,04 mg/L) resulta em zero.',
    impactType: 'anulacao_total',
    confidenceScore: 98,
    whenToUse: ['Testes com resultado medido igual ou inferior a 0,04 mg de álcool por litro de ar alveolar'],
    whenNotToUse: ['Medições superiores a 0,05 mg/L'],
    requirements: ['Cópia do cupom do etilômetro demonstrando medição inferior ao limite de tolerância'],
    legalBase: 'Tabela do Anexo I da Resolução CONTRAN nº 432/2013',
    resolutions: ['Resolução CONTRAN nº 432/2013, Art. 6º, II e Anexo I'],
    relatedJurisprudence: ['TJ-RS; AC 70081298341; Vigésima Segunda Câmara Cível'],
    requiredDocuments: ['Extrato impresso do teste de ar alveolar'],
    observations: 'Medições até 0,04 mg/L têm valor considerado zero e não configuram infração.',
    formattedParagraphs: [
      {
        heading: '1. Da Aplicação da Margem de Tolerância Regulamentar de 0,04 mg/L',
        text: 'Conforme a Tabela do Anexo I da Resolução CONTRAN nº 432/2013, medições de até 0,04 mg/L resultam em valor considerado igual a 0,00 mg/L, impondo-se a imediata liberação do condutor.',
      },
    ],
  },
  {
    id: 'ARG-029',
    code: 'LEI_SECA_FALTA_TESTE_EM_BRANCO',
    category: 'merito',
    title: 'Ausência de Teste em Branco Prévio no Etilômetro',
    description: 'Vício metrológico decorrente da falta de realização do teste em branco (verificação de resíduos) antes da coleta do condutor.',
    impactType: 'anulacao_total',
    confidenceScore: 87,
    whenToUse: ['Aparelhos de etilômetro que não realizaram o auto-teste de limpeza de câmara antes do exame'],
    whenNotToUse: ['Aparelhos com ciclo automático completo registrado no ticket'],
    requirements: ['Extrato do etilômetro omitindo o teste em branco com valor 0,00'],
    legalBase: 'Portaria INMETRO nº 369/2021',
    resolutions: ['Resolução CONTRAN nº 432/2013'],
    relatedJurisprudence: ['TJ-SP; Apelação 1009123-44.2021.8.26.0053'],
    requiredDocuments: ['Cupom impresso pelo etilômetro'],
    observations: 'O teste em branco garante que a câmara de medição estava isenta de vapores residuais.',
    formattedParagraphs: [
      {
        heading: '1. Da Exigência de Purga e Teste em Branco no Procedimento Metrológico',
        text: 'A confiabilidade do exame exige a comprovação de ausência de resíduos alcoólicos prévios na câmara do instrumento medidor.',
      },
    ],
  },
  {
    id: 'ARG-030',
    code: 'LEI_SECA_USO_MEDICAMENTO_ALCOOLICO_ENXAGUANTE',
    category: 'merito',
    title: 'Álcool Bucal Residual por Uso Recente de Antisséptico / Medicamento Homeopático',
    description: 'Demonstração de falso positivo decorrente de enxaguante bucal utilizado minutos antes da abordagem sem ingestão de bebida.',
    impactType: 'anulacao_total',
    confidenceScore: 90,
    whenToUse: ['Casos em que o condutor solicitou contraprova após 15 minutos e teve o pedido negado pelo agente'],
    whenNotToUse: ['Ingestão comprovada de bebidas etílicas'],
    requirements: ['Declaração fática e requerimento de contraprova no momento da abordagem'],
    legalBase: 'Manual do Etilômetro c/c Princípio da Verdade Real',
    resolutions: ['Resolução CONTRAN nº 432/2013'],
    relatedJurisprudence: ['TJ-SC; AC 5003412-11.2021.8.24.0023; 2ª Câmara de Direito Público'],
    requiredDocuments: ['Declaração do condutor e eventual frasco/comprovante'],
    observations: 'O manual do fabricante exige intervalo mínimo de 15 minutos após uso de substâncias orais.',
    formattedParagraphs: [
      {
        heading: '1. Da Influência de Vapores Bucais e do Dever de Aguardar 15 Minutos',
        text: 'O protocolo técnico internacional determina que o teste deve aguardar 15 minutos quando informado o uso recente de enxaguante ou medicamento contendo álcool para evitar a captura de álcool bucal.',
      },
    ],
  },

  // ==========================================
  // 6. CINTO DE SEGURANÇA (ARG-031 a ARG-034)
  // ==========================================
  {
    id: 'ARG-031',
    code: 'CINTO_EQUIVOCO_ROUPA_ESCURA',
    category: 'merito',
    title: 'Erro de Visualização por Uso de Vestimenta Escura Idêntica ao Cinto',
    description: 'Desconstituição da autuação de cinto sem abordagem quando a roupa escura do motorista camufla o cinto afivelado.',
    impactType: 'anulacao_total',
    confidenceScore: 89,
    whenToUse: ['Multas do Art. 167 sem abordagem em que o condutor trajava terno, casaco ou camiseta preta'],
    whenNotToUse: ['Autuações com abordagem confirmada pelo motorista'],
    requirements: ['Foto do cinto de segurança do veículo e declaração das vestimentas'],
    legalBase: 'Art. 281, I do CTB',
    resolutions: ['Resolução CONTRAN nº 985/2022 (MBFT)'],
    relatedJurisprudence: ['TJ-SP; Recurso Inominado 1001234-99.2022.8.26.0016'],
    requiredDocuments: ['Foto do interior do veículo com o cinto escuro'],
    observations: 'O agente de trânsito à distância é suscetível a ilusão de ótica por contraste de cores.',
    formattedParagraphs: [
      {
        heading: '1. Do Erro de Percepção Visual e Ausência de Certeza Material',
        text: 'A semelhança tonal entre o cinto de segurança e a vestimenta do condutor gera dúvida razoável que impede a imposição de penalidade sancionatória sem a devida abordagem.',
      },
    ],
  },
  {
    id: 'ARG-032',
    code: 'CINTO_ISENCAO_MEDICA_COMPROVADA',
    category: 'merito',
    title: 'Isenção Médica Obrigatória de Uso do Cinto de Segurança (Res. CONTRAN 985/2022)',
    description: 'Atipicidade da conduta de condutor ou passageiro portador de laudo médico que desaconselha o uso do cinto por cirurgia ou condição clínica.',
    impactType: 'anulacao_total',
    confidenceScore: 98,
    whenToUse: ['Motoristas ou passageiros com atestado médico oficial de isenção de cinto'],
    whenNotToUse: ['Condutores sem patologia clínica'],
    requirements: ['Laudo médico prévio com indicação de CID e justificativa de dispensa'],
    legalBase: 'Art. 167 do CTB c/c Manual Brasileiro de Fiscalização de Trânsito',
    resolutions: ['Resolução CONTRAN nº 985/2022 (MBFT - Ficha 518-51)'],
    relatedJurisprudence: ['TJ-MG; Apelação Cível 1.0000.20.098123-1/001'],
    requiredDocuments: ['Laudo médico oficial com CRM'],
    observations: 'A ficha do enquadramento do MBFT prevê expressamente a excludente por motivo médico.',
    formattedParagraphs: [
      {
        heading: '1. Da Excludente Legal por Motivo de Isenção Médica Comprovada',
        text: 'Havendo contraindicação médica comprovada por laudo técnico contemporâneo aos fatos, afasta-se a tipicidade da infração do Art. 167 do CTB.',
      },
    ],
  },
  {
    id: 'ARG-033',
    code: 'CINTO_PASSAGEIRO_RESPONSABILIDADE_COMPROVADA',
    category: 'merito',
    title: 'Autuação Indevida do Condutor por Cinto de Passageiro em Ônibus/Van',
    description: 'Afastamento de responsabilidade em transporte coletivo onde o dever de fiscalização individual é mitigado.',
    impactType: 'anulacao_total',
    confidenceScore: 87,
    whenToUse: ['Veículos de transporte complementar/vans com aviso sonoro e placas afixadas'],
    whenNotToUse: ['Automóveis de passeio particulares'],
    requirements: ['Comprovante de afixação de aviso de obrigatoriedade do cinto'],
    legalBase: 'Art. 167 do CTB c/c Resolução CONTRAN nº 985/2022',
    resolutions: ['Resolução CONTRAN nº 985/2022'],
    relatedJurisprudence: ['TJ-RJ; Apelação 0012398-33.2021.8.19.0001'],
    requiredDocuments: ['Fotos dos avisos no veículo'],
    observations: 'O motorista profissional cumpre seu dever ao advertir e disponibilizar o cinto aos passageiros.',
    formattedParagraphs: [
      {
        heading: '1. Do Cumprimento do Dever de Advertência pelo Condutor Profissional',
        text: 'Em transporte coletivo, a disponibilização do cinto e a afixação de avisos regulamentares afastam a culpa do condutor pela conduta voluntária e isolada do passageiro.',
      },
    ],
  },
  {
    id: 'ARG-034',
    code: 'CINTO_VEICULO_ANTIGO_ISENTO_FABRICACAO',
    category: 'merito',
    title: 'Veículo Antigo Isento de Cinto de 3 Pontos ou no Banco Traseiro de Fábrica',
    description: 'Atipicidade da autuação para veículos clássicos/antigos que não possuíam o dispositivo na data de sua fabricação original.',
    impactType: 'anulacao_total',
    confidenceScore: 99,
    whenToUse: ['Veículos antigos (fusca, kombi, etc.) fabricados antes das resoluções que tornaram o cinto obrigatório'],
    whenNotToUse: ['Veículos modernos'],
    requirements: ['Cópia do CRLV comprovando o ano de fabricação do veículo'],
    legalBase: 'Resolução CONTRAN nº 14/1998 e 985/2022',
    resolutions: ['Resolução CONTRAN nº 14/1998'],
    relatedJurisprudence: ['TJ-RS; Recurso Inominado 71009123841'],
    requiredDocuments: ['CRLV do veículo antigo'],
    observations: 'Não se pode exigir equipamento não obrigatório à época da homologação do modelo.',
    formattedParagraphs: [
      {
        heading: '1. Da Não Retroatividade de Normas de Equipamentos Obrigatórios a Veículos Antigos',
        text: 'Veículos fabricados anteriormente à vigência das normas compulsórias de cintos submetem-se aos requisitos técnicos de sua época de fabricação original.',
      },
    ],
  },

  // ==========================================
  // 7. LICENCIAMENTO & DOCUMENTAÇÃO (ARG-035 a ARG-038)
  // ==========================================
  {
    id: 'ARG-035',
    code: 'LICENCIAMENTO_PAGO_ATRASO_DETRAN_SISTEMICO',
    category: 'merito',
    title: 'Tributos e Taxas de Licenciamento Quitados Tempestivamente com Atraso Sistêmico no DETRAN',
    description: 'Nulidade da autuação por falta de licenciamento (Art. 230, V) quando comprovado o pagamento prévio de IPVA e taxas pelo cidadão.',
    impactType: 'anulacao_total',
    confidenceScore: 95,
    whenToUse: ['Multas do Art. 230, V onde os comprovantes bancários são anteriores à data da abordagem'],
    whenNotToUse: ['Veículos com débitos de IPVA ou multas pendentes não pagas'],
    requirements: ['Comprovantes bancários de quitação do IPVA, DPVAT e taxa de licenciamento'],
    legalBase: 'Art. 131, § 2º do CTB c/c Princípio da Boa-Fé do Administrado',
    resolutions: ['Resolução CONTRAN nº 985/2022'],
    relatedJurisprudence: ['TJ-SP; Apelação 1004123-55.2022.8.26.0053; 1ª Câmara de Direito Público'],
    requiredDocuments: ['Comprovantes bancários autenticados de pagamento dos tributos'],
    observations: 'A mora do órgão administrativo na baixa bancária não pode prejudicar o condutor diligente.',
    formattedParagraphs: [
      {
        heading: '1. Da Comprovação de Quitação Prévia e Inexistência de Culpa do Administrado',
        text: 'Estando todos os tributos devidamente quitados no sistema financeiro antes da data da autuação, a demora no processamento do CRLV-e pelo DETRAN não pode ensejar penalidade.',
      },
    ],
  },
  {
    id: 'ARG-036',
    code: 'PORTE_DOCUMENTO_DISPENSADO_SISTEMA_INFORMATIZADO',
    category: 'merito',
    title: 'Dispensabilidade do Porte Físico de Documento com Acesso a Sistema Informatizado (Art. 232 CTB)',
    description: 'Atipicidade da infração de falta de porte de CNH ou CRLV quando o agente tem meios informatizados de checagem do RENAVAM/RENACH.',
    impactType: 'anulacao_total',
    confidenceScore: 97,
    whenToUse: ['Autuações do Art. 232 onde o sistema do SENATRAN/DETRAN estava plenamente acessível ao agente'],
    whenNotToUse: ['Locais remotos sem nenhuma cobertura de internet onde o agente declarou a impossibilidade'],
    requirements: ['Cópia do prontuário demonstrando situação regular do veículo e CNH'],
    legalBase: 'Art. 133, parágrafo único e Art. 159, § 1º-A do CTB (com redação da Lei 14.071/2020)',
    resolutions: ['Resolução CONTRAN nº 985/2022'],
    relatedJurisprudence: ['TJ-MG; Apelação Cível 1.0000.22.091234-1/001'],
    requiredDocuments: ['Extrato do aplicativo CDT (Carteira Digital de Trânsito)'],
    observations: 'A Lei 14.071/2020 expressamente dispensou o porte físico mediante consulta sistêmica.',
    formattedParagraphs: [
      {
        heading: '1. Da Expressa Dispensa Legal do Porte de Documentos com Acesso Sistêmico',
        text: 'A legislação de trânsito em vigor dispensa o porte da CNH e do CRLV quando o agente de fiscalização puder acessar os sistemas informatizados de registro público.',
      },
    ],
  },
  {
    id: 'ARG-037',
    code: 'LICENCIAMENTO_CRLV_DIGITAL_DISPONIVEL_CDT',
    category: 'merito',
    title: 'Validade Jurídica Plena do CRLV Digital no Aplicativo CDT (Portaria SENATRAN)',
    description: 'Invalidade de autuação cominada sob pretexto de recusa ao documento eletrônico disponível na Carteira Digital de Trânsito.',
    impactType: 'anulacao_total',
    confidenceScore: 99,
    whenToUse: ['Casos em que o agente exigiu o papel moeda físico em detrimento do app oficial'],
    whenNotToUse: ['Condutor desprovido de documento digital e físico'],
    requirements: ['Captura de tela do aplicativo oficial CDT demonstrando a versão digital válida'],
    legalBase: 'Art. 131 c/c Resolução CONTRAN nº 809/2020',
    resolutions: ['Resolução CONTRAN nº 809/2020'],
    relatedJurisprudence: ['TJ-DFT; Acórdão 1391283; 2ª Turma Recursal'],
    requiredDocuments: ['Cópia do CRLV-e com QR Code'],
    observations: 'O CRLV-e em meio digital possui a mesma validade jurídica do documento impresso.',
    formattedParagraphs: [
      {
        heading: '1. Da Equivalência e Eficácia Plena dos Documentos Digitais Oficiais',
        text: 'A apresentação do documento por meio do aplicativo oficial Carteira Digital de Trânsito cumpre integralmente a exigência legal de porte e identificação.',
      },
    ],
  },
  {
    id: 'ARG-038',
    code: 'PLACA_MERCOSUL_DIVERGENCIA_CARACTERES',
    category: 'formal',
    title: 'Erro de Conversão de Placa Cinza para Padrão Mercosul no Registro do AIT',
    description: 'Nulidade por digitação errônea da letra correspondente ao segundo algarismo na conversão das placas Mercosul.',
    impactType: 'anulacao_total',
    confidenceScore: 91,
    whenToUse: ['AIT onde o agente trocou o número pela letra errada do padrão Mercosul (ex: 2 por C ao invés de B)'],
    whenNotToUse: ['Placas com correspondência correta'],
    requirements: ['Cópia do CRLV e espelho do AIT demonstrando o caractere incorreto'],
    legalBase: 'Art. 280, III do CTB c/c Resolução CONTRAN nº 969/2022',
    resolutions: ['Resolução CONTRAN nº 969/2022'],
    relatedJurisprudence: ['TJ-SP; Recurso Inominado 1002341-99.2021.8.26.0053'],
    requiredDocuments: ['CRLV do veículo'],
    observations: 'O erro no caractere da placa torna o AIT inconsistente quanto à identidade do veículo.',
    formattedParagraphs: [
      {
        heading: '1. Da Inconsistência na Identificação do Veículo no Auto de Infração',
        text: 'O preenchimento inexato da placa de identificação no padrão Mercosul contamina o auto de inconsistência insanável, impondo seu arquivamento.',
      },
    ],
  },

  // ==========================================
  // 8. MULTAS NIC PESSOA JURÍDICA (ARG-039 a ARG-041)
  // ==========================================
  {
    id: 'ARG-039',
    code: 'NIC_PJ_INDICACAO_TEMPESTIVA_NAO_PROCESSADA',
    category: 'merito',
    title: 'Multa NIC Indevida: Real Condutor Indicado Tempestivamente pela Empresa',
    description: 'Nulidade da multa por Não Indicação de Condutor quando a empresa protocolou o FICI tempestivamente pelos canais do órgão.',
    impactType: 'anulacao_total',
    confidenceScore: 96,
    whenToUse: ['Multas NIC com comprovante de protocolo ou postagem da indicação do condutor dentro do prazo'],
    whenNotToUse: ['Empresas que deixaram transcorrer o prazo sem protocolar o FICI'],
    requirements: ['Comprovante de protocolo eletrônico ou aviso de recebimento (AR) da indicação'],
    legalBase: 'Art. 257, § 7º e § 8º do CTB c/c Resolução CONTRAN nº 918/2022',
    resolutions: ['Resolução CONTRAN nº 918/2022, Art. 9º'],
    relatedJurisprudence: ['STJ; REsp 1.774.891/SP; Segunda Turma', 'TJ-SP; Apelação 1012398-11.2023.8.26.0053'],
    requiredDocuments: ['Comprovante de protocolo do FICI tempestivo'],
    observations: 'A inércia do órgão em processar o FICI tempestivo não autoriza a lavratura da multa NIC.',
    formattedParagraphs: [
      {
        heading: '1. Da Ilegalidade da Multa NIC Diante da Indicação Tempestiva do Condutor',
        text: 'Comprovado o protocolo tempestivo da indicação do condutor pelo proprietário pessoa jurídica, resta afastada a hipótese sancionatória do Artigo 257, § 8º do CTB.',
      },
    ],
  },
  {
    id: 'ARG-040',
    code: 'NIC_PJ_NULIDADE_REFLEXA_AIT_ORIGINARIO',
    category: 'preliminar',
    title: 'Nulidade Reflexa da Multa NIC em Virtude da Anulação do AIT Originário',
    description: 'Extinção compulsória da multa NIC quando o Auto de Infração originário foi cancelado por decadência ou nulidade formal.',
    impactType: 'anulacao_total',
    confidenceScore: 98,
    whenToUse: ['Casos em que o AIT gerador da multa NIC foi arquivado na Defesa Prévia ou JARI'],
    whenNotToUse: ['AIT originário hígido e confirmado'],
    requirements: ['Certidão de cancelamento ou decisão de arquivamento do AIT originário'],
    legalBase: 'Princípio da Gravitação Jurídica (o acessório segue a sorte do principal)',
    resolutions: ['Resolução CONTRAN nº 918/2022'],
    relatedJurisprudence: ['STJ; AgInt no REsp 1.892.341/SP; Primeira Turma'],
    requiredDocuments: ['Cópia da decisão de deferimento do AIT originário'],
    observations: 'Anulada a autuação principal, desfazem-se automaticamente todas as penalidades acessórias.',
    formattedParagraphs: [
      {
        heading: '1. Da Extinção da Multa NIC em Virtude da Insubsistência do Auto Originário',
        text: 'Em atenção ao princípio da gravitação jurídica, a decretação de nulidade do auto de infração originário extingue de pleno direito a penalidade acessória de não indicação de condutor.',
      },
    ],
  },
  {
    id: 'ARG-041',
    code: 'NIC_PJ_AUSENCIA_NOTIFICACAO_PREVIA_MULTA_NIC',
    category: 'formal',
    title: 'Falta de Notificação de Autuação Específica da Multa NIC (Súmula 312 STJ)',
    description: 'Nulidade do processo sancionatório da multa NIC que foi cobrada diretamente sem emissão de Notificação de Autuação autônoma.',
    impactType: 'anulacao_total',
    confidenceScore: 93,
    whenToUse: ['Órgãos que enviam o boleto da multa NIC diretamente sem fase de Defesa Prévia'],
    whenNotToUse: ['Procedimentos que expediram a Notificação de Autuação da NIC'],
    requirements: ['Comprovação de recebimento direto da Notificação de Penalidade sem Notificação de Autuação'],
    legalBase: 'Art. 281 do CTB c/c Súmula 312 do STJ',
    resolutions: ['Resolução CONTRAN nº 918/2022'],
    relatedJurisprudence: ['TJ-SP; Apelação Cível 1009123-99.2022.8.26.0053; 1ª Câmara de Direito Público'],
    requiredDocuments: ['Notificação de penalidade da multa NIC'],
    observations: 'A multa NIC exige contraditório e ampla defesa autônomos.',
    formattedParagraphs: [
      {
        heading: '1. Da Necessidade de Dupla Notificação no Procedimento da Multa NIC',
        text: 'A imposição da penalidade do Art. 257, § 8º do CTB constitui novo ato administrativo sancionatório que reclama a prévia expedição de Notificação da Autuação específica.',
      },
    ],
  },

  // ==========================================
  // 9. SUSPENSÃO & CASSAÇÃO DA CNH (ARG-042 a ARG-047)
  // ==========================================
  {
    id: 'ARG-042',
    code: 'SUSPENSAO_RETROATIVIDADE_40_PONTOS_LEI_14071',
    category: 'merito',
    title: 'Aplicação Retroativa da Escala de 40 Pontos da Lei 14.071/2020 (Tema 1.097 STJ)',
    description: 'Retroatividade de norma administrativa mais benéfica para processos de suspensão por pontuação instaurados antes da vigência da Lei 14.071/20.',
    impactType: 'anulacao_total',
    confidenceScore: 96,
    whenToUse: ['Processos de suspensão da CNH em andamento com pontuação entre 20 e 39 pontos sem 2 infrações gravíssimas'],
    whenNotToUse: ['Processos já com trânsito em julgado e cumprimento de penalidade concluído'],
    requirements: ['Espelho do prontuário de CNH demonstrando o histórico infracional'],
    legalBase: 'Art. 261, I do CTB (redação da Lei nº 14.071/2020) c/c Art. 5º, XL da CF/88',
    resolutions: ['Resolução CONTRAN nº 723/2018 (com alterações da Res. 844/2021)'],
    relatedJurisprudence: ['STJ; Tema Repetitivo 1.097 (REsp 1.869.589/SP)', 'TJ-SP; Enunciado Cível'],
    requiredDocuments: ['Prontuário da CNH no DETRAN'],
    observations: 'O STJ fixou que a lei mais benéfica retroage aos processos administrativos em curso.',
    formattedParagraphs: [
      {
        heading: '1. Da Eficácia Retroativa da Lei nº 14.071/2020 aos Processos em Trâmite',
        text: 'Conforme tese vinculante firmada pelo Superior Tribunal de Justiça no Tema 1.097, o novo limite escalonado de 40 pontos aplica-se retroativamente a todos os processos de suspensão não transitados em julgado.',
      },
    ],
  },
  {
    id: 'ARG-043',
    code: 'SUSPENSAO_FALTA_TRANSITO_EM_JULGADO_MULTAS',
    category: 'preliminar',
    title: 'Instauração Prematura de PSDD sem o Trânsito em Julgado das Multas Integrantes',
    description: 'Nulidade do processo de suspensão por pontos instruído com infrações que ainda possuem recursos administrativos pendentes na JARI ou CETRAN.',
    impactType: 'anulacao_total',
    confidenceScore: 94,
    whenToUse: ['PSDD instaurado com multas cujos recursos administrativos ainda não foram definitivamente julgados'],
    whenNotToUse: ['PSDD onde todas as multas já tiveram recursos indeferidos em 2ª instância'],
    requirements: ['Comprovantes de interposição de recurso com efeito suspensivo nas multas componentes'],
    legalBase: 'Art. 285, § 3º c/c Art. 290, parágrafo único do CTB',
    resolutions: ['Resolução CONTRAN nº 723/2018, Art. 7º'],
    relatedJurisprudence: ['TJ-SP; Apelação Cível 1009841-88.2021.8.26.0053; 2ª Câmara de Direito Público'],
    requiredDocuments: ['Espelho de acompanhamento dos recursos pendentes'],
    observations: 'Pontos de multas sub judice não podem ser computados para atingimento do teto de suspensão.',
    formattedParagraphs: [
      {
        heading: '1. Da Impossibilidade de Cômputo de Pontuação sob Efeito Suspensivo',
        text: 'A pontuação decorrente de infração com recurso administrativo pendente de julgamento goza de efeito suspensivo automático, não podendo subsidiar a abertura de processo punitivo de suspensão da CNH.',
      },
    ],
  },
  {
    id: 'ARG-044',
    code: 'SUSPENSAO_PRESCRICAO_QUINQUENAL_PUNITIVA',
    category: 'preliminar',
    title: 'Prescrição Quinquenal da Pretensão Punitiva do DETRAN (Lei 9.873/1999)',
    description: 'Extinção do processo de suspensão instaurado após mais de 5 anos da data da última infração do prontuário.',
    impactType: 'anulacao_total',
    confidenceScore: 97,
    whenToUse: ['Notificação de instauração do PSDD recebida mais de 5 anos após a data do fato infracional'],
    whenNotToUse: ['Procedimentos instaurados dentro do prazo quinquenal'],
    requirements: ['Demonstração do transcurso de mais de 5 anos entre o fato e a notificação de abertura do PSDD'],
    legalBase: 'Art. 1º da Lei Federal nº 9.873/1999 c/c Resolução CONTRAN nº 723/2018, Art. 24',
    resolutions: ['Resolução CONTRAN nº 723/2018, Art. 24, I'],
    relatedJurisprudence: ['STJ; AgInt no REsp 1.782.391/RJ; Segunda Turma'],
    requiredDocuments: ['Histórico do processo administrativo do DETRAN'],
    observations: 'O direito de punir prescreve em 5 anos contados da data da infração ou do encerramento da esfera recursal.',
    formattedParagraphs: [
      {
        heading: '1. Da Consumação da Prescrição Quinquenal da Pretensão Punitiva',
        text: 'O decurso de prazo superior a 5 (cinco) anos sem a prática de atos interruptivos extingue a pretensão punitiva do Estado, impondo-se o arquivamento definitivo do processo de suspensão.',
      },
    ],
  },
  {
    id: 'ARG-045',
    code: 'CASSACAO_AUSENCIA_DIRECAO_PESSOAL_CONDUTOR',
    category: 'merito',
    title: 'Inocorrência de Direção Durante a Suspensão: Veículo Conduzido por Terceiro',
    description: 'Nulidade do processo de cassação da CNH (Art. 263, I) quando a infração na vigência da suspensão ocorreu sem abordagem e o veículo estava na posse de outrem.',
    impactType: 'anulacao_total',
    confidenceScore: 95,
    whenToUse: ['Processos de cassação baseados em multas de radar ou talonário sem abordagem'],
    whenNotToUse: ['Condutor flagrado e identificado presencialmente pelo agente no volante'],
    requirements: ['Declaração do terceiro com firma reconhecida ou contrato de alienação/locação do veículo'],
    legalBase: 'Art. 263, I do CTB c/c Princípio da Intranscendência das Penas (Art. 5º, XLV da CF/88)',
    resolutions: ['Resolução CONTRAN nº 723/2018'],
    relatedJurisprudence: ['STJ; REsp 1.698.412/SP; Segunda Turma', 'TJ-SP; Apelação 1004123-99.2021.8.26.0053'],
    requiredDocuments: ['Declaração de real condutor', 'Cópia da CNH do terceiro'],
    observations: 'A propriedade do veículo não autoriza presumir que o condutor suspenso dirigia.',
    formattedParagraphs: [
      {
        heading: '1. Da Necessidade de Comprovação da Efetiva Direção do Veículo pelo Suspenso',
        text: 'A penalidade extrema de cassação do documento de habilitação exige prova inequívoca de que o condutor penalizado estava efetivamente ao volante, sendo nula a sanção fundada em presunção decorrente da mera titularidade do bem.',
      },
    ],
  },
  {
    id: 'ARG-046',
    code: 'CASSACAO_NULIDADE_SUSPENSAO_ORIGINARIA',
    category: 'preliminar',
    title: 'Nulidade Originária do Processo de Suspensão que Contamina a Cassação Subsequente',
    description: 'Anulação da cassação da CNH quando comprovado que o processo de suspensão anterior padecia de vício de notificação ou prescrição.',
    impactType: 'anulacao_total',
    confidenceScore: 93,
    whenToUse: ['Casos em que a suspensão anterior foi aplicada sem envio de notificação para o endereço correto do condutor'],
    whenNotToUse: ['Suspensão anterior plenamente válida e cumprida'],
    requirements: ['Cópia dos autos do PSDD originário evidenciando a ausência de notificação válida'],
    legalBase: 'Art. 5º, LV da CF/88 c/c Teoria dos Frutos da Árvore Envenenada no Direito Administrativo',
    resolutions: ['Resolução CONTRAN nº 723/2018'],
    relatedJurisprudence: ['TJ-SP; Apelação Cível 1002341-88.2020.8.26.0053; 6ª Câmara de Direito Público'],
    requiredDocuments: ['Cópia do processo de suspensão anterior'],
    observations: 'O ato nulo não gera efeitos jurídicos válidos capazes de fundamentar a cassação.',
    formattedParagraphs: [
      {
        heading: '1. Do Efeito Cascata da Nulidade do Processo Administrativo Originário',
        text: 'A inexistência de notificação válida no processo de suspensão originário retira a eficácia da restrição, tornando manifestamente ilegítima a subsequente instauração do procedimento de cassação da habilitação.',
      },
    ],
  },
  {
    id: 'ARG-047',
    code: 'SUSPENSAO_CURSO_RECICLAGE_CUMPRIDO_TEMPESTIVAMENTE',
    category: 'merito',
    title: 'Cumprimento Antecipado de Curso de Reciclagem e Desbloqueio da CNH',
    description: 'Regularização cadastral quando o condutor realizou o curso preventivo de reciclagem previsto no Art. 261, § 5º do CTB.',
    impactType: 'anulacao_total',
    confidenceScore: 98,
    whenToUse: ['Motoristas profissionais (EAR) que realizaram o curso ao atingirem 30 pontos'],
    whenNotToUse: ['Condutores sem EAR na carteira'],
    requirements: ['Certificado de conclusão de curso de reciclagem preventivo homologado'],
    legalBase: 'Art. 261, § 5º do CTB c/c Resolução CONTRAN nº 723/2018',
    resolutions: ['Resolução CONTRAN nº 723/2018'],
    relatedJurisprudence: ['TJ-SP; Mandado de Segurança 1009123-11.2022.8.26.0053'],
    requiredDocuments: ['Certificado emitido pelo CFC credenciado'],
    observations: 'O curso preventivo zera a pontuação acumulada para condutores profissionais.',
    formattedParagraphs: [
      {
        heading: '1. Da Quitação da Pontuação pelo Curso Preventivo de Reciclagem (Art. 261, §5º)',
        text: 'A realização do curso preventivo de reciclagem pelo condutor profissional titular de CNH com a observação EAR opera a eliminação dos pontos computados nos 12 meses anteriores.',
      },
    ],
  },

  // ==========================================
  // 10. PRELIMINARES GERAIS & CONSTITUCIONAIS (ARG-048 a ARG-052)
  // ==========================================
  {
    id: 'ARG-048',
    code: 'DECADENCIA_NOTIFICACAO_AUTUACAO_30_DIAS',
    category: 'preliminar',
    title: 'Decadência do Direito de Punir: Notificação Expedida após 30 Dias (Art. 281, II CTB)',
    description: 'Extinção definitiva da pretensão punitiva da Administração Pública em virtude da expedição ou postagem da Notificação da Autuação (NA) após o prazo decadencial de 30 dias da infração.',
    impactType: 'anulacao_total',
    confidenceScore: 99,
    whenToUse: ['Notificação de Autuação postada nos Correios com data superior a 30 dias da data do cometimento da infração'],
    whenNotToUse: ['Notificação expedida ou postada eletronicamente dentro do prazo de 30 dias'],
    requirements: ['Demonstração da data do fato e da data da emissão/postagem da Notificação de Autuação'],
    legalBase: 'Art. 281, parágrafo único, inciso II do CTB c/c Súmula 312 do STJ',
    resolutions: ['Resolução CONTRAN nº 918/2022, Art. 3º'],
    relatedJurisprudence: [
      'STJ; Súmula 312',
      'STJ; REsp 1.092.793/DF; Primeira Seção (Tema 127 dos Recursos Repetitivos)',
      'TJ-SP; Apelação 1002341-55.2023.8.26.0053; 1ª Câmara de Direito Público',
    ],
    requiredDocuments: [
      'Cópia da Notificação da Autuação contendo a data da infração e a data de expedição/postagem',
    ],
    observations: 'O prazo de 30 dias é decadencial de ordem pública e extingue o próprio direito de punir da autoridade.',
    formattedParagraphs: [
      {
        heading: '1. Da Consumação do Prazo Decadencial de 30 Dias para Expedição da Notificação',
        text: 'Preceitua de forma categórica o Artigo 281, parágrafo único, inciso II do Código de Trânsito Brasileiro que o Auto de Infração será arquivado e seu registro julgado insubsistente se, no prazo máximo de 30 (trinta) dias, não for expedida a notificação da autuação.',
      },
      {
        heading: '2. Do Entendimento Consolidado pelo Superior Tribunal de Justiça (Tema Repetitivo 127)',
        text: 'O Egrégio Superior Tribunal de Justiça, ao julgar o Recurso Especial Repetitivo nº 1.092.793/DF (Tema 127), pacificou que a inobservância do prazo decadencial de 30 dias para a expedição da Notificação de Autuação implica a perda do direito de punir do Estado, ensejando a anulação definitiva do auto e impedindo a sua reautuação.',
      },
    ],
  },
  {
    id: 'ARG-049',
    code: 'NULIDADE_SUMULA_312_STJ_FALTA_NOTIFICACAO',
    category: 'preliminar',
    title: 'Cerceamento de Defesa por Ausência de Dupla Notificação (Súmula 312 STJ)',
    description: 'Nulidade insanável de processo de trânsito em que o órgão autuador aplicou penalidade sem a comprovação de envio da Notificação de Autuação prévia.',
    impactType: 'anulacao_total',
    confidenceScore: 98,
    whenToUse: ['Recebimento direto de boleto de cobrança sem oportunidade de apresentar Defesa Prévia'],
    whenNotToUse: ['Notificação comprovadamente entregue no endereço cadastrado no RENACH/RENAVAM'],
    requirements: ['Extrato do histórico de notificações com ausência de código de rastreamento postal (AR)'],
    legalBase: 'Art. 5º, LIV e LV da CF/88 c/c Súmula 312 do STJ',
    resolutions: ['Resolução CONTRAN nº 918/2022'],
    relatedJurisprudence: ['STJ; Súmula 312', 'TJ-SP; Súmula 127 do STJ'],
    requiredDocuments: ['Cópia da notificação de penalidade e certidão do DETRAN'],
    observations: 'O procedimento de trânsito é bifásico e obrigatório.',
    formattedParagraphs: [
      {
        heading: '1. Da Garantia Constitucional da Dupla Notificação e Súmula 312 do STJ',
        text: 'A supressão da primeira fase procedimental (Notificação de Autuação) fulmina o processo de nulidade absoluta por cerceamento das garantias constitucionais do contraditório e da ampla defesa.',
      },
    ],
  },
  {
    id: 'ARG-050',
    code: 'INCOMPETENCIA_TERRITORIAL_ORGAO_AUTUADOR',
    category: 'formal',
    title: 'Incompetência Funcional e Territorial do Órgão Fiscalizador (Arts. 21 e 24 CTB)',
    description: 'Nulidade de autuação lavrada por autoridade municipal em rodovia de competência federal/estadual sem convênio formal vigente.',
    impactType: 'anulacao_total',
    confidenceScore: 94,
    whenToUse: ['Multas aplicadas por municípios em rodovias estaduais (DER) ou federais (PRF/DNIT) sem convênio publicado'],
    whenNotToUse: ['Vias municipais urbanas ou rodovias com convênio bilateral vigente'],
    requirements: ['Certidão de circunscrição viária ou ausência de publicação de convênio no Diário Oficial'],
    legalBase: 'Art. 21, Art. 22 e Art. 24 da Lei nº 9.503/1997',
    resolutions: ['Resolução CONTRAN nº 985/2022'],
    relatedJurisprudence: ['STJ; REsp 1.458.912/MG; Primeira Turma'],
    requiredDocuments: ['Mapa oficial do trecho viário e extrato do AIT'],
    observations: 'O ato praticado por autoridade incompetente é nulo de pleno direito.',
    formattedParagraphs: [
      {
        heading: '1. Do Vício de Competência e Violação ao Princípio da Legalidade Estrita',
        text: 'A partilha de competências administrativas entre órgãos federais, estaduais e municipais é matéria de ordem pública, gerando a nulidade insanável da autuação praticada fora dos limites territoriais autorizados.',
      },
    ],
  },
  {
    id: 'ARG-051',
    code: 'CONVERSAO_OBRIGATORIA_ADVERTENCIA_ART267',
    category: 'merito',
    title: 'Direito Subjetivo à Conversão em Advertência por Escrito (Art. 267 do CTB)',
    description: 'Imposição obrigatória da conversão de multa leve ou média em advertência por escrito quando o condutor não cometeu infrações nos últimos 12 meses (Lei 14.071/2020).',
    impactType: 'conversao_advertencia',
    confidenceScore: 99,
    whenToUse: ['Infrações leves ou médias em que o condutor não possui pontuação nos 12 meses anteriores'],
    whenNotToUse: ['Infrações de natureza grave ou gravíssima ou condutores reincidentes'],
    requirements: ['Certidão de prontuário da CNH sem infrações nos últimos 12 meses'],
    legalBase: 'Art. 267 do Código de Trânsito Brasileiro (com redação da Lei nº 14.071/2020)',
    resolutions: ['Resolução CONTRAN nº 918/2022, Art. 10'],
    relatedJurisprudence: ['TJ-SP; Apelação Cível 1004589-11.2022.8.26.0053; 3ª Câmara de Direito Público'],
    requiredDocuments: ['Extrato de prontuário e histórico de CNH'],
    observations: 'A Lei 14.071/2020 transformou o ato de discricionário em poder-dever vinculado da autoridade.',
    formattedParagraphs: [
      {
        heading: '1. Do Direito Subjetivo do Condutor à Conversão em Advertência por Escrito',
        text: 'A nova redação do Artigo 267 do CTB impõe à autoridade de trânsito a obrigação de converter a penalidade de multa em advertência por escrito para infrações leves ou médias cometidas por condutores não reincidentes em 12 meses.',
      },
    ],
  },
  {
    id: 'ARG-052',
    code: 'AUSENCIA_MOTIVACAO_DESPACHO_PADRONIZADO_JARI',
    category: 'formal',
    title: 'Nulidade da Decisão por Falta de Motivação Expressa (Art. 50 Lei 9.784/99 e Art. 93, IX CF)',
    description: 'Nulidade absoluta do indeferimento do recurso julgado por carimbo ou despacho padronizado sem análise dos argumentos do cidadão.',
    impactType: 'anulacao_total',
    confidenceScore: 95,
    whenToUse: ['Decisões de 1ª ou 2ª instância que utilizam fórmula genérica sem rebater as teses arguidas'],
    whenNotToUse: ['Decisões colegiadas que fundamentaram ponto a ponto o indeferimento'],
    requirements: ['Cópia da decisão / ata de julgamento da JARI ou CETRAN'],
    legalBase: 'Art. 50 da Lei Federal nº 9.784/1999 c/c Art. 93, IX e Art. 5º, LV da CF/88',
    resolutions: ['Regimento Interno das JARIs e CONTRAN'],
    relatedJurisprudence: ['STF; ARE 748.371/MT (Tema 660); Plenário', 'TJ-SP; Apelação 1012398-88.2021.8.26.0053'],
    requiredDocuments: ['Cópia da decisão administrativa recorrida'],
    observations: 'O dever de fundamentação concreta dos atos decisórios administrativos é indeclinável.',
    formattedParagraphs: [
      {
        heading: '1. Do Vício de Nulidade por Falta de Fundamentação no Julgamento Administrativo',
        text: 'A decisão administrativa colegiada que indefere recurso mediante despacho genérico e padronizado viola o dever de motivação do Artigo 50 da Lei nº 9.784/1999 e cerceia o direito de defesa do administrado.',
      },
    ],
  },
];
